[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@oppenzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "@4337/=lib/account-abstraction/contracts/",
    "@uniswap-v3-core/=lib/uniswap-v3-core/contracts/",
    "@uniswap-v3-periphery=lib/uniswap-v3-periphery/",
    "@utils/=src/utils/",
    "@interfaces/=src/interfaces/",
    "@libraries/=src/libraries/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "uniswap-v3-core/=lib/uniswap-v3-core/",
    "uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
